# # Simulated daily request to your render project so that the service doesn't go down
# name: Ping URL every 15 minutes

# on:
#   schedule:
#     - cron: "*/15 * * * *"
#   workflow_dispatch:

# jobs:
#   curl-website:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Ping URL
#         run: |
#           curl -s -o /dev/null -w "%{http_code}\n" https://service.paisa-planner.com
#       # - name: Run cURL on Website
#       #   run: curl -I WEBSITE_URL

